# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-19 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161115_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
