# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-15 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20161115_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='targets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.Room'),
        ),
    ]
