# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-19 20:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20161115_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 19, 20, 58, 15, 269304, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
