# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-29 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_room_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='password',
        ),
    ]
